on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_roms:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          mkdir hashes
          deno run -A --unstable --no-check update_repos.ts
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "chore: update repos ${timestamp}"
          git push